export const occupationOptions = [
  "Atendente",
  "Auxiliar Administrativo",
  "Auxiliar de Limpeza",
  "Desenvolvedor Front-end",
  "Desenvolvedor Back-end",
  "Desenvolvedor Fullstack",
  "Designer",
  "Diretor Executivo (CEO)",
  "Gerente de Projetos",
  "Analista de Dados",
  "Suporte Técnico",
  "TI - Infraestrutura",
  "TI - Segurança da Informação",
  "Contador",
  "Advogado",
  "Estagiário",
  "RH",
  "Marketing",
  "Vendas",
  "Outro",
];
